# Generated by Django 3.0.4 on 2020-04-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mllearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='class_name',
            field=models.CharField(default='no name', max_length=30),
        ),
    ]
