# Generated by Django 3.0.4 on 2020-04-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mllearning', '0004_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
